USE Final234

SELECT ORDER_DETAILS.ORDER_ID,
ORDER_DETAILS.PRODUCT_ID,
PRODUCTS.PRODUCT_NAME,
ORDER_DETAILS.UNIT_PRICE,
ORDER_DETAILS.QUANTITY,
ORDER_DETAILS.DISCOUNT, 
(concat('$',  CAST(((ORDER_DETAILS.UNIT_PRICE * ORDER_DETAILS.QUANTITY)- (ORDER_DETAILS.UNIT_PRICE * ORDER_DETAILS.QUANTITY * ORDER_DETAILS.DISCOUNT))
AS DECIMAL(7,2))))  AS [TOTAL_PRICE]
FROM ORDER_DETAILS 
INNER JOIN PRODUCTS
ON ORDER_DETAILS.PRODUCT_ID = PRODUCTS.PRODUCT_ID
WHERE ORDER_DETAILS.ORDER_ID = 10248; 